DEFAULT_INPUT_STREAM_FILE = '../../datasets/small.csv'
DEFAULT_STREAM_PARAMETER_FILE = '../../datasets/small.parameters'
DEFAULT_TRAIN_SAMPLES = 8
DEFAULT_TEST_SAMPLES = 2
DEFAULT_BUFFER_SIZE = 10
DEFAULT_MAX_SAMPLES = None
DEFAULT_DELTA_THRESHOLD = 5
