DEFAULT_INPUT_STREAM_FILE = '../../datasets/small.csv'
DEFAULT_STREAM_PARAMETER_FILE = '../../datasets/small.parameters'
DEFAULT_TRAIN_SAMPLES = 1000
DEFAULT_TEST_SAMPLES = 200
DEFAULT_BUFFER_SIZE = 1200
DEFAULT_MAX_SAMPLES = None
DEFAULT_DELTA_THRESHOLD = 5
